### PR TITLE
Unicode Names

### PR DESCRIPTION
**Pull request by facelessuser**
Add support for \N in search and replace.  Add logic to catch when references like \N, \p, \P, and \g are incomplete and raise an exception. At a little testing (still more to do).

### CODE REVIEW

**Comment by facelessuser** [comment]
Py3.3 will get dropped, so that can be ignored. Looks like some new PY3.7 weirdness, so I'll take a look at that.

**Comment by facelessuser** [comment]
To be honest, I think this is a Python 3.7 bug:

```
tests/test_bregex.py:816: AssertionError
___________________ TestReplaceTemplate.test_normal_escaping ___________________
self = <tests.test_bregex.TestReplaceTemplate testMethod=test_normal_escaping>
    def test_normal_escaping(self):
        """Test normal escaped slash."""
    
        text = "This is a test of normal escaping!"
        pattern = regex.compile(r"(.*)")
        repl_pattern = r'\e \\e \\\e \\\\e \\\\\e'
        expand = bregex.compile_replace(pattern, repl_pattern)
        m = pattern.match(text)
        results = expand(m)
        results2 = pattern.sub(repl_pattern, text)
    
>       self.assertEqual(results2, results)
E       AssertionError: '\\e \\e \\\\e \\\\e \\\\\\e\\e \\e \\\\e \\\\e \\\\\\e' != '\\e \\e \\\\e \\\\e \\\\\\e'
E       - \e \e \\e \\e \\\e\e \e \\e \\e \\\e
E       + \e \e \\e \\e \\\e
tests/test_bregex.py:802: AssertionError
```

It look to be substituting twice.  This doesn't fail on any other Python, so I am inclined to believe 3.7 greedy capture is flawed and is possibly returning two matches which makes no sense, but I have not investigated further as I don't have a locally installed Py3.7.  I probably won't address it in this pull, but investigate in another issue.

**Comment by facelessuser** [comment]
Just for curiosity, I may put in a log statement just to see what Py3.7 pattern looks like after our translation.  Maybe do a pure Py3.7 greedy search and replace to see how it behaves.

**Comment by facelessuser** [comment]
Looking closer at this, I now realize PY3.7 is failing for `regex` not `re`.  So it is most likely a support issue for `regex` on PY3.7.  This makes more sense as it is likely that no PY3.7 work has been done on `regex` yet.  It would be good to investigate and create an issue there when I have a chance, my real concern was breaking on PY3.7 which we are not breaking.

**Comment by facelessuser** [comment]
Regex module was recently updated and now all passes are testing except coverage.

**Comment by serhiy-storchaka** [comment]
I suggest to use `r"(.+)"` instead of `r"(.*)"`. The behavior of zero-width matches is not intuitive and can be changed in future in both `re` and `regex` modules.

**Comment by facelessuser** [comment]
@serhiy-storchaka Thanks for the info.  That was kind of the conclusion I came to after looking at the actual changes `regex` recently made, specifically addressing zero-width behavior for 3.7.  I'll make a note of this to update tests accordingly.  Seems like there is some churning going on in the re module moving forward.

**Comment by serhiy-storchaka** [comment]
The behavior has been changed in 3.7a4: https://bugs.python.org/issue32308. Now it is uniform across all functions: **split**(), **sub**(), **findall**(), **finditer**().

**Pull request merged**
