### PR TITLE
Update deploy to build wheels for each supported python version

### PR DESCRIPTION
**Pull request by facelessuser**
Adds wheels for #146

### CODE REVIEW

**Comment by facelessuser** [comment]
@gir-bot lgtm

**Comment by henryiii** [comment]
I would recommend building all the parts, using actions/upload-artifact@v2, then then doing the submit once in a download job with needs. Also 1.4.1 is the current version of the pypa action, IIRC.

**Comment by henryiii** [comment]
That way, if there was a problem building a wheel, it would stop before submitting the files.

**Comment by facelessuser** [comment]
@henryiii, thanks for the info. I'll definitely upgrade to the latest pypa action. It is one of those things that wasn't broke, so it kept slipping my mind. As for artifacts, it is something to consider. It hasn't been needed for most of my projects as both sdist and bdist_wheel have been built in one step. This is the first project where I am uploading through multiple steps.

I'll take a look in the future. It definitely sounds like a good idea.

**Pull request merged**
